### PR TITLE
Test AVIF support 1

### PR DESCRIPTION
**Pull request by eldadfux**
Added AVIF support which requires php8.1. 

Related:

* https://github.com/appwrite/appwrite/issues/7043

### CODE REVIEW

**Review by lohanidamodar — CHANGES_REQUESTED** [review]
Looks good. May be remove tests/.DS_Store file.

**Comment by eldadfux** [comment]
Fixed.

**Review by TorstenDittmann — CHANGES_REQUESTED** [review]
We should adapt `composer.json` so it requires PHP 8.1

**Review by christyjacob4 — APPROVED** [review]

**Comment by eldadfux** [comment]
> We should adapt `composer.json` so it requires PHP 8.1

Fixed.

**Review by lohanidamodar — APPROVED** [review]

**Pull request merged**
